server:
  port: 8081

ssbe:
  cassandra:
    host: "127.0.0.1"
    port: 9042
  es:
    seeds: "127.0.0.1"
    port: 9200
    bulkSize: 500
    transport:
      sniff: true
  kafka:
    bootstrap-server: "127.0.0.1:9092"
    topic: search_sync